package org.nsu.fit.services.rest;

import org.nsu.fit.services.generator.FakerGenerator;
import org.nsu.fit.services.generator.UserGenerator;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CredentialsPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.nsu.fit.services.rest.data.PlanPojo;
import org.nsu.fit.shared.JsonMapper;

import java.util.UUID;

public class RestApiClient {
    // Note: change url if you want to use the docker compose.
//    private static final String REST_URI = "http://localhost:8080/tm-backend/rest";
    private static final String REST_URI = "http://localhost:8089/tm-backend/rest";

    private final HttpClient httpClient = new HttpClient(REST_URI);

    private final UserGenerator userGenerator = new FakerGenerator();

    public AccountTokenPojo authenticate(String login, String pass) {
        CredentialsPojo credentialsPojo = new CredentialsPojo(login, pass);

        return httpClient.post(
                "authenticate",
                JsonMapper.toJson(credentialsPojo, true),
                AccountTokenPojo.class,
                null
        );
    }

    public CustomerPojo createAutoGeneratedCustomer(AccountTokenPojo accountToken) {
        return createCustomer(userGenerator.generateCustomer(), accountToken);
    }

    public CustomerPojo createCustomer(CustomerPojo customerPojo, AccountTokenPojo accountToken) {
        return httpClient.post(
                "customers",
                JsonMapper.toJson(customerPojo, true),
                CustomerPojo.class,
                accountToken
        );
    }

    public void deleteCustomer(UUID id, AccountTokenPojo accountToken) {
        httpClient.delete(
                "customers/" + id,
                Void.class,
                accountToken
        );
    }

    public PlanPojo createPlan(PlanPojo planPojo, AccountTokenPojo accountToken) {
        return httpClient.post(
                "plans",
                JsonMapper.toJson(planPojo, true),
                PlanPojo.class,
                accountToken
        );
    }

    public void deletePlan(UUID id, AccountTokenPojo accountToken) {
        httpClient.delete("plans/" + id, Void.class, accountToken);
    }

    public CustomerPojo getCurrentUserProfile(AccountTokenPojo accountToken) {
        return httpClient.get("me", CustomerPojo.class, accountToken);
    }
}
