FROM gradle:6.1.1-jdk8 AS GRADLE_BUILD
WORKDIR /test-methods/tm-backend
COPY ./ ./
RUN gradle build

FROM tomcat:9.0
RUN apt-get update && apt-get -y upgrade
RUN sed -i 's/port="8080"/port="8089"/' /usr/local/tomcat/conf/server.xml
COPY --from=GRADLE_BUILD test-methods/tm-backend/build/libs/ /usr/local/tomcat/webapps/

WORKDIR /usr/local/tomcat
