package org.nsu.fit.tests.ui;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.nsu.fit.tests.ui.screen.LoginScreen;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.util.List;

public class DeleteCustomerTest extends BaseUITest {

    @Test(description = "Delete customer via UI.")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Delete customer feature")
    public void deleteCustomer() throws Exception {
        apiClient.createAutoGeneratedCustomer(adminToken);
        List<CustomerPojo> customersBefore = apiClient.getCustomers(adminToken);

        new LoginScreen(browser)
            .loginAsAdmin()
            .deleteFirstCustomerAndConfirm();

        Thread.sleep(1000);
        List<CustomerPojo> customersAfter = apiClient.getCustomers(adminToken);

        Assert.assertEquals(customersBefore.size(), customersAfter.size() + 1);
    }
}
