package org.nsu.fit.tests.ui;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.nsu.fit.tests.ui.screen.LoginScreen;
import org.testng.annotations.Test;

public class LogoutTest extends BaseUITest {

    @Test(description = "Logout as admin")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Logout feature")
    public void logoutAsAdmin() {
        new LoginScreen(browser)
                .loginAsAdmin()
                .logout();
    }

    @Test(description = "Logout as customer")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Logout feature")
    public void logoutAsCustomer() {
        CustomerPojo customer = apiClient.createAutoGeneratedCustomer(adminToken);

        new LoginScreen(browser)
                .loginAsCustomer(customer.login, customer.pass)
                .logout();
    }
}
