package org.nsu.fit.tests.ui;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import lombok.SneakyThrows;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.nsu.fit.services.rest.data.SubscriptionPojo;
import org.nsu.fit.tests.ui.screen.LoginScreen;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.util.List;

public class SubscribePlanTest extends BaseUITest {

    private static final int MONEY_TO_ADD = 777;

    private final CustomerPojo customer = apiClient.createAutoGeneratedCustomer(adminToken);
    private final AccountTokenPojo userToken = apiClient.authenticate(customer.login, customer.pass);

    @Test(description = "Subscribe plan")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Subscribe plan feature")
    @SneakyThrows
    public void subscribePlan() {
        apiClient.createPlan(fakerGenerator.generatePlan(), adminToken);

        new LoginScreen(browser)
                .loginAsCustomer(customer.login, customer.pass)
                .topUpBalance()
                .fillMoney(MONEY_TO_ADD)
                .clickSubmit()
                .subscribeFirstPlan();

        List<SubscriptionPojo> subscriptions = apiClient.getAvailableSubscriptions(userToken);
        Assert.assertFalse(subscriptions.isEmpty());
    }
}
