package org.nsu.fit.tests.ui;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import lombok.SneakyThrows;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.nsu.fit.services.rest.data.PlanPojo;
import org.nsu.fit.services.rest.data.SubscriptionPojo;
import org.nsu.fit.tests.ui.screen.LoginScreen;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.util.List;
import java.util.UUID;

public class UnsubscribePlanTest extends BaseUITest {

    private final CustomerPojo customer = apiClient.createAutoGeneratedCustomer(adminToken);
    private final AccountTokenPojo userToken = apiClient.authenticate(customer.login, customer.pass);

    @Test(description = "Unsubscribe plan")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Unsubscribe plan feature")
    @SneakyThrows
    public void subscribePlan() {
        apiClient.createPlan(fakerGenerator.generatePlan(), adminToken);
        createSubscription();

        new LoginScreen(browser)
                .loginAsCustomer(customer.login, customer.pass)
                .unsubscribeFirstPlan();

        Thread.sleep(1000);
        List<SubscriptionPojo> subscriptions = apiClient.getAvailableSubscriptions(userToken);
        Assert.assertTrue(subscriptions.isEmpty());
    }

    private void createSubscription() {
        PlanPojo plan = apiClient.createPlan(fakerGenerator.generatePlan(), adminToken);

        SubscriptionPojo subscriptionPojo = new SubscriptionPojo();
        subscriptionPojo.customerId = customer.id;
        subscriptionPojo.planId = plan.getId();
        subscriptionPojo.planName = UUID.randomUUID().toString();
        subscriptionPojo.planFee = 1;

        apiClient.createSubscription(subscriptionPojo, userToken);
    }
}
