package org.nsu.fit.tests.api;

import lombok.NoArgsConstructor;
import org.nsu.fit.services.generator.FakerGenerator;
import org.nsu.fit.services.rest.RestApiClient;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeSuite;

@NoArgsConstructor
public class BaseITTest {
    protected static AccountTokenPojo adminToken;

    protected final RestApiClient restClient = new RestApiClient();
    protected final FakerGenerator fakerGenerator = new FakerGenerator();

    protected AccountTokenPojo customerToken;

    @BeforeSuite
    public void init() {
        adminToken = restClient.authenticate("admin", "setup");
    }

    @BeforeClass
    public void initCustomerToken() {
        CustomerPojo customerPojo = restClient.createAutoGeneratedCustomer(adminToken);
        customerToken = restClient.authenticate(customerPojo.login, customerPojo.pass);
    }
}
