package org.nsu.fit.tests.api;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.testng.annotations.Test;

public class CreateCorrectCustomerAsAdminTest extends BaseITTest {

    @Test(description = "Create correct customer")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Customer feature.")
    public void createCorrectCustomer() {
        restClient.createAutoGeneratedCustomer(adminToken);
    }

}
