package org.nsu.fit.tests.api;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.ContactPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.testng.Assert;
import org.testng.annotations.Test;

public class GetCurrentUserTest extends BaseITTest {

    @Test(description = "Get current admin user profile")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Access feature.")
    public void getCurrentAdminUserProfile() {
        ContactPojo me = restClient.getCurrentUserProfile(adminToken);
        Assert.assertEquals(me.login, "admin");
    }

    @Test(description = "Get current customer user profile")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Access feature.")
    public void getCurrentCustomerUserProfile() {
        CustomerPojo customerPojo = restClient.createAutoGeneratedCustomer(adminToken);
        AccountTokenPojo customerToken = restClient.authenticate(customerPojo.login, customerPojo.pass);

        ContactPojo me = restClient.getCurrentUserProfile(customerToken);
        Assert.assertEquals(me.login, customerPojo.login);
    }
}
