package org.nsu.fit.tests.api;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.testng.Assert;
import org.testng.annotations.Test;

public class TryToCreateResourcesAsCustomer extends BaseITTest {

    @Test(description = "Create correct plan as customer")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Access feature.")
    public void createCorrectPlan() {
        Assert.assertThrows(
                RuntimeException.class,
                () -> restClient.createPlan(
                        fakerGenerator.generatePlan(),
                        customerToken
                )
        );
    }

    @Test(description = "Create correct customer as customer")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Access feature.")
    public void createCorrectCustomer() {
        Assert.assertThrows(
                RuntimeException.class,
                () -> restClient.createAutoGeneratedCustomer(customerToken)
        );
    }
}
