package org.nsu.fit.tests.api;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class TryToCreateAsCustomer extends BaseITTest {

    protected AccountTokenPojo customerToken;

    @BeforeClass
    public void initCustomerToken() {
        CustomerPojo customerPojo = restClient.createAutoGeneratedCustomer(adminToken);
        customerToken = restClient.authenticate(customerPojo.login, customerPojo.pass);
    }

    @Test(description = "Create correct plan as customer")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Access feature.")
    public void createCorrectPlan() {
        restClient.createPlan(
                fakerGenerator.generatePlan(),
                customerToken
        );
    }

    @Test(description = "Create correct customer as customer")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Access feature.")
    public void createCorrectCustomer() {
        restClient.createAutoGeneratedCustomer(customerToken);
    }
}
